export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const FETCH_SINGLE_POST_COMMENTS = 'FETCH_SINGLE_POST_COMMENTS';
export const FETCH_SINGLE_POST = 'FETCH_SINGLE_POST';
export const VOTE_POST = 'VOTE_POST';
export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';